import { Inspection } from './types';

export const inspections: Inspection[] = [
  {
    id: 'inspection-001',
    title: 'Safety inspection',
    locationName: 'Warehouse #12',
    locationType: 'WAREHOUSE',
    address: 'ул. Абая, 145, Алматы',
    status: 'IN_PROGRESS',
    priority: 'CRITICAL',
    scheduledAt: 'Today, 10:00',
    deadlineAt: 'Today, 18:00',
    completedItemsCount: 18,
    totalItemsCount: 24,
    issuesCount: 3,
    criticalIssuesCount: 1,
    updatedAt: '12 min ago',
  },
  {
    id: 'inspection-002',
    title: 'Store compliance check',
    locationName: 'Green Market — Point 4',
    locationType: 'STORE',
    address: 'пр. Достык, 87, Алматы',
    status: 'ASSIGNED',
    priority: 'HIGH',
    scheduledAt: 'Today, 14:30',
    deadlineAt: 'Tomorrow, 12:00',
    completedItemsCount: 0,
    totalItemsCount: 18,
    issuesCount: 0,
    criticalIssuesCount: 0,
    updatedAt: '35 min ago',
  },
  {
    id: 'inspection-003',
    title: 'Office facility review',
    locationName: 'North Tower, Floor 9',
    locationType: 'OFFICE',
    address: 'ул. Тимирязева, 42, Алматы',
    status: 'COMPLETED',
    priority: 'MEDIUM',
    scheduledAt: 'Yesterday, 11:00',
    deadlineAt: null,
    completedItemsCount: 31,
    totalItemsCount: 31,
    issuesCount: 2,
    criticalIssuesCount: 0,
    updatedAt: 'Yesterday',
  },
  {
    id: 'inspection-004',
    title: 'Apartment handover inspection',
    locationName: 'Residential complex Aurora',
    locationType: 'APARTMENT',
    address: 'ул. Кабанбай батыра, 19, Астана',
    status: 'SUBMITTED',
    priority: 'LOW',
    scheduledAt: 'June 25, 09:30',
    deadlineAt: null,
    completedItemsCount: 22,
    totalItemsCount: 22,
    issuesCount: 1,
    criticalIssuesCount: 0,
    updatedAt: 'June 25',
  },
  {
    id: 'inspection-005',
    title: 'Fire safety inspection',
    locationName: 'Logistics Center A',
    locationType: 'WAREHOUSE',
    address: 'Индустриальная зона, блок 7, Астана',
    status: 'SYNC_ERROR',
    priority: 'HIGH',
    scheduledAt: 'Today, 16:00',
    deadlineAt: 'Today, 20:00',
    completedItemsCount: 9,
    totalItemsCount: 16,
    issuesCount: 2,
    criticalIssuesCount: 0,
    updatedAt: 'Offline changes pending',
  },
];